language: python
python:
  - "2.7"
  - "3.3"

install:
  # Install `slack_to_trello`
  - python setup.py develop

  # Install dev requirements
  - pip install -r requirements-dev.txt

script:
  # Run our tests
  - ./test.sh

notifications:
  email: false
