language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  # Install requirements and dev requirements
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

  # Set up `slack_to_trello` as its own dependency
  - python setup.py develop

script:
  # Run our tests
  - ./test.sh

notifications:
  email: false
